name: Build Jekyll

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1 # see https://github.com/ruby/setup-ruby
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - run: bundle exec jekyll build

